
language: android
android:
    components:
    - platform-tools
    - build-tools-28.0.3
    - tools
    - android-28
    - android-27
    - android-22
    - extra-android-m2repository
    - extra-android-support
before_install:
  - chmod +x gradlew
  - yes | sudo sdkmanager --licenses

script:
    - ./gradlew assemble